### ISSUE TITLE
Plugin will not work on folia 1.21.1

### ISSUE THREAD

**Issue by megatron0001** [ocelotpotpie/FreedomChat#60]
[17:32:17 INFO]: [FreedomChat] Enabling FreedomChat v1.7.0
[17:32:17 ERROR]: Error occurred while enabling FreedomChat v1.7.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/network/chat/Component
        at FreedomChat-Paper-1.7.0(2).jar/ru.bk.oharass.freedomchat.FreedomChat.onEnable(FreedomChat.java:27) ~[FreedomChat-Paper-1.7.0(2).jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:646) ~[?:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:595) ~[?:?]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:780) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:527) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1281) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:357) ~[folia-1.21.1.jar:1.21.1-DEV-88e0907]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.network.chat.Component
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 13 more
[17:32:17 INFO]: [FreedomChat] Disabling FreedomChat v1.7.0

**Comment by Kichura** [comment]
You compiled Folia wrong, Please use `./gradlew createMojmapBundlerJar` to build the software instead and ensure you got the correct JAR.

**Comment by ocelotpotpie** [comment]
As said above, looks like an incorrect compile.

You also really really shouldn't be using Folia 1.21.1. There's been a bunch of changes since 1.21.1. Grab the 1.21.8 download from the Paper website and you can skip the decompile errors.
